name: ChunkDungeons
version: Dev-Re-1.0
main: bonnett.Main
api-version: "1.13"
authors:
  - ShiftySnowWolf
  - Bonn2
depend:
  - WorldEdit
  - LuckPerms
commands:
  chunkdungeons:
    description: Main command
    usage: /chunkdungeons <generate/reloadpalettes>