name: ChunkDungeons
version: Dev-Re-1.0
main: bonnett.Main
api-version: "1.13"
authors:
  - ShiftySnowWolf
  - Bonn2
depend:
  - WorldEdit
softdepend:
  - LuckPerms
loadbefore:
  - LuckPerms
commands:
  chunkdungeons:
    description: Main command
    aliases:
      - cd
    permission: chunkdungeons.admin
    permission-message: You do not have permission to use this command!
    usage: /chunkdungeons [generate|reload|reloadconfig|reloadpalettes]