name: HackAndSlash
version: ${project.version}
main: bonnett.HackAndSlash
api-version: "1.13"
authors:
  - ShiftySnowWolf
  - Bonn2
depend:
  - WorldEdit
commands:
  generatedungeon:
    description: Generates a dungeon.
    usage: /generatedungeon <TYPE> <SIZE>