#Chunk Dungeons configuration file

#<<Generation Logic>>#
#Delay in ticks between chunk generation. Default: 10
generation_speed: 10
#Mamimum dungeon size in a chunk radius + 1 Default: 20
max_size: 20
#Minimum dungeon size in a chunk radius + 1 Default: 5
min_size: 5
#Allow generation in peaceful. Default: false
generate_peaceful: false

#<<Palette Configuration>>#
#Wether or not you want to include the palette template. Default: false
include_template: false